a=int(input("Enter the First Number: "))
b=int(input("Enter the second number:"))
print("sum: ",a+b,"Division: ",a/b)
var1=(a>b)
print("Is a greater than b?:",var1)
var2=(a==b)
print("Are a and b equal?:",var2)
print("Logical And:",(a>b)and(b<a))
print("Logical OR:",(a==b)or(a<b))

